excel-file-upload-django/excel_upload/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace="myapp")),
]

excel-file-upload-django/myapp/urls.py
from django.urls import path

from . import views

app_name = "myapp"

urlpatterns = [
    path('', views.index, name='index'),
]

excel-file-upload-django/myapp/models.py
from django.db import models

# Create your models here.

excel-file-upload-django/myapp/views.py
from django.shortcuts import render
import openpyxl
import pandas as pd

def index(request):
    if "GET" == request.method:
        return render(request, 'myapp/index.html', {})
    else:
        excel_file = request.FILES["excel_file"]

        # you may put validations here to check extension or file size
        xl = pd.ExcelFile(excel_file)
        names =xl.sheet_names
        df = xl.parse(names[0])       
        writer = pd.ExcelWriter('output1.xlsx')
        df.to_excel(writer,sheet_name='sheet1',index=False)
        writer.save()        

        return render(request, 'myapp/index.html', { })

excel-file-upload-django/myapp/templates/myapp/index.html
<html>
    <head>
        <title>
            Excel file upload and processing : Django Example : ThePythonDjango.Com
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <h1>Put your file over here</h1>
        <form action="{% url "myapp:index" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>
    </body>
</html>